import 'dates.dart';
import 'models.dart';

/// The example home from the prototype. Dates are relative to today so the
/// attention list always has something in it (an expiring warranty, a closing
/// return window, maintenance due, a used item with an unknown transfer).
List<Item> exampleItems([DateTime? now]) {
  now ??= today();
  String d(int months, [int extraDays = 0]) =>
      toIsoDate(addDays(addMonths(now!, months), extraDays));
  final t = DateTime.now().millisecondsSinceEpoch;
  return [
    Item(
      id: 'x1',
      name: 'LG French-door refrigerator',
      brand: 'LG',
      model: 'LRFVS3006S',
      serial: '407KRAB12345',
      category: Category.appliance,
      room: 'Kitchen',
      acquired: d(-10),
      price: 2899,
      retailer: 'Home Depot',
      warrantyMonths: 24,
      evidence: const [Evidence(EvidenceKind.receipt)],
      maintenance: [
        MaintenanceTask(
          task: 'Replace water filter',
          everyMonths: 6,
          lastDone: d(-5, -20),
        ),
        MaintenanceTask(
          task: 'Check air filter',
          everyMonths: 6,
          lastDone: d(-2),
        ),
      ],
      createdAt: t - 9,
    ),
    Item(
      id: 'x2',
      name: 'Samsung 65-inch QN90D',
      brand: 'Samsung',
      model: 'QN65QN90DAFXZC',
      serial: '0B7Z3CDX400123',
      category: Category.electronics,
      room: 'Living room',
      acquired: d(-11, -8),
      price: 1799.99,
      retailer: 'Best Buy',
      warrantyMonths: 12,
      evidence: const [
        Evidence(EvidenceKind.receipt),
        Evidence(EvidenceKind.email),
      ],
      createdAt: t - 8,
    ),
    Item(
      id: 'x3',
      name: 'LG OLED C4 65-inch',
      brand: 'LG',
      model: 'OLED65C4PUA',
      serial: 'ABC123456',
      category: Category.electronics,
      room: 'Studio',
      acquisition: Acquisition.used,
      acquired: d(0, -3),
      price: 900,
      retailer: 'Facebook Marketplace',
      originalPurchase: d(-18),
      originalRetailer: 'Best Buy',
      warrantyMonths: 24,
      warrantySource: WarrantySource.typical,
      evidence: const [
        Evidence(EvidenceKind.marketplace),
        Evidence(EvidenceKind.seller),
      ],
      createdAt: t - 7,
    ),
    Item(
      id: 'x4',
      name: 'MacBook Pro 14-inch',
      brand: 'Apple',
      model: 'MX2H3LL/A',
      serial: 'C02XK1ABCDEF',
      category: Category.electronics,
      room: 'Studio',
      acquisition: Acquisition.used,
      acquired: d(0, -21),
      price: 1600,
      retailer: 'Private seller',
      warrantyMonths: 12,
      warrantySource: WarrantySource.typical,
      transfer: Transfer.transferable,
      evidence: const [Evidence(EvidenceKind.user)],
      createdAt: t - 6,
    ),
    Item(
      id: 'x5',
      name: 'Poäng armchair',
      brand: 'IKEA',
      category: Category.furniture,
      room: 'Living room',
      acquired: d(-26),
      price: 149,
      retailer: 'IKEA',
      createdAt: t - 5,
    ),
    Item(
      id: 'x6',
      name: 'Kallax shelf unit',
      brand: 'IKEA',
      category: Category.furniture,
      room: 'Studio',
      acquired: d(-4),
      price: 119,
      retailer: 'IKEA',
      evidence: const [Evidence(EvidenceKind.card)],
      createdAt: t - 4,
    ),
    Item(
      id: 'x7',
      name: 'Eve Energy smart plug',
      brand: 'Eve',
      model: '20EBO8301',
      category: Category.smarthome,
      room: 'Bedroom',
      acquired: d(0, -25),
      price: 49.99,
      retailer: 'Amazon',
      returnDays: 30,
      warrantyMonths: 24,
      warrantySource: WarrantySource.typical,
      createdAt: t - 3,
    ),
    Item(
      id: 'x8',
      name: 'Dyson V15 Detect',
      brand: 'Dyson',
      model: 'SV22',
      serial: 'XA1-CA-PAB1234A',
      category: Category.appliance,
      room: 'Hallway',
      acquired: d(-15),
      price: 949.99,
      retailer: 'Costco',
      warrantyMonths: 24,
      mfrConfirmed: true,
      evidence: const [
        Evidence(EvidenceKind.receipt),
        Evidence(EvidenceKind.registration),
      ],
      maintenance: [
        MaintenanceTask(
          task: 'Wash filter',
          everyMonths: 1,
          lastDone: d(-1, -20),
        ),
      ],
      createdAt: t - 2,
    ),
    Item(
      id: 'x9',
      name: 'Sony HT-A5000 soundbar',
      brand: 'Sony',
      model: 'HT-A5000',
      category: Category.electronics,
      room: 'Living room',
      acquired: d(-30),
      price: 1199,
      retailer: 'Best Buy',
      warrantyMonths: 12,
      evidence: const [Evidence(EvidenceKind.receipt)],
      createdAt: t - 1,
    ),
    Item(
      id: 'x10',
      name: 'Yamaha acoustic guitar',
      brand: 'Yamaha',
      model: 'FG800',
      category: Category.gear,
      room: 'Studio',
      acquisition: Acquisition.gift,
      acquired: d(-40),
      evidence: const [Evidence(EvidenceKind.photo)],
      value: 250,
      createdAt: t,
    ),
  ];
}
